[versions]
kotlin = "2.3.0"
dokka = "2.1.0"
mavenPublish = "0.35.0"
axionRelease = "1.21.1"

brigadier = "1.3.10"
#adventure = "4.26.1"
adventure = "4.16.0"
paperApi = "1.21.10-R0.1-SNAPSHOT"
junitJupiter = "5.14.2"
mockk = "1.14.7"
jsonassert = "1.5.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axionRelease" }

[libraries]
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paperApi" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert" }
